import { StyleSheet } from "react-native";

export const colors = {
  background: "#F7F4EC",
  card: "#FFFFFF",
  cardSoft: "#EFE7FF",
  primary: "#2B0055",
  primaryDark: "#230044",
  primaryLight: "#EEE9FF",
  primaryBright: "#3A0EC6",
  text: "#10162F",
  textSoft: "#383354",
  textMuted: "#7C829A",
  border: "#ECE8DF",
  borderStrong: "#C9C2DA",
  success: "#23B24B",
  white: "#FFFFFF",
  shadow: "#1E1230",
};

const shadow = {
  shadowColor: colors.shadow,
  shadowOffset: {
    width: 0,
    height: 10,
  },
  shadowOpacity: 0.08,
  shadowRadius: 20,
  elevation: 4,
};

const softShadow = {
  shadowColor: colors.shadow,
  shadowOffset: {
    width: 0,
    height: 5,
  },
  shadowOpacity: 0.06,
  shadowRadius: 12,
  elevation: 2,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 112,
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.25,
  },
  headerSpacer: {
    width: 44,
    height: 44,
  },
  closeButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  logoMarca: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  logoIconCircle: {
    width: 35,
    height: 35,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  logo: {
    fontSize: 31,
    lineHeight: 36,
    fontWeight: "800",
    fontStyle: "italic",
    color: colors.primary,
    letterSpacing: -1.4,
  },
  profileButton: {
    width: 47,
    height: 47,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  stationCard: {
    minHeight: 126,
    marginBottom: 18,
    padding: 14,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  stationImage: {
    width: 88,
    height: 88,
    marginRight: 12,
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "#DDEAD9",
  },
  stationImageSky: {
    height: 35,
    backgroundColor: "#DDEAF1",
  },
  stationImageGround: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 28,
    backgroundColor: "#BBCDB1",
  },
  chargerMock: {
    position: "absolute",
    left: 29,
    bottom: 18,
    width: 31,
    height: 54,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  chargerMockText: {
    marginBottom: 3,
    fontSize: 9,
    fontWeight: "800",
    color: colors.white,
  },
  stationInfo: {
    flex: 1,
    minWidth: 0,
  },
  badgesRow: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.primaryLight,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textSoft,
  },
  stationName: {
    marginBottom: 5,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.5,
  },
  stationAddress: {
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 18,
    color: colors.textMuted,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusDot: {
    width: 9,
    height: 9,
    marginRight: 7,
    borderRadius: 5,
    backgroundColor: colors.success,
  },
  statusText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textMuted,
  },
  heartButton: {
    width: 42,
    height: 42,
    marginLeft: 8,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  formCard: {
    marginBottom: 16,
    padding: 18,
    borderRadius: 26,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  title: {
    marginBottom: 5,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.5,
  },
  subtitle: {
    marginBottom: 18,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  overallCard: {
    marginBottom: 12,
    padding: 13,
    borderRadius: 21,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  overallIconCircle: {
    width: 43,
    height: 43,
    marginRight: 12,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
  },
  overallContent: {
    flex: 1,
    minWidth: 0,
  },
  overallTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.text,
  },
  overallDescription: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  criteriaList: {
    overflow: "hidden",
    borderWidth: 1,
    borderRadius: 21,
    borderColor: colors.border,
  },
  criterionRow: {
    minHeight: 68,
    paddingHorizontal: 13,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.card,
  },
  criterionIconCircle: {
    width: 38,
    height: 38,
    marginRight: 12,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
  },
  criterionContent: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  criterionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
  },
  criterionDescription: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  starsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  starButton: {
    width: 28,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  starButtonPressed: {
    opacity: 0.62,
    transform: [
      {
        scale: 0.94,
      },
    ],
  },
  commentBlock: {
    marginTop: 17,
  },
  commentHeader: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  commentLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
  },
  optionalText: {
    marginLeft: 5,
    fontSize: 13,
    color: colors.textMuted,
  },
  commentInput: {
    minHeight: 96,
    paddingHorizontal: 14,
    paddingTop: 13,
    paddingBottom: 30,
    borderWidth: 1,
    borderRadius: 17,
    borderColor: colors.borderStrong,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSoft,
    backgroundColor: colors.card,
  },
  counterText: {
    alignSelf: "flex-end",
    marginTop: -27,
    marginRight: 13,
    fontSize: 12,
    fontWeight: "700",
    color: colors.textMuted,
  },
  toggleGrid: {
    marginTop: 18,
    gap: 12,
  },
  toggleCard: {
    flex: 1,
    minHeight: 94,
    padding: 13,
    borderRadius: 20,
    justifyContent: "space-between",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  toggleCardSelected: {
    borderColor: colors.primary,
    backgroundColor: "#FCFBFF",
  },
  toggleTextArea: {
    marginBottom: 12,
  },
  toggleTitle: {
    marginBottom: 4,
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  toggleDescription: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  togglePill: {
    alignSelf: "flex-start",
    height: 34,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    borderColor: colors.primary,
    backgroundColor: colors.card,
    gap: 6,
  },
  togglePillSelected: {
    backgroundColor: colors.primary,
  },
  togglePillText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.primary,
  },
  togglePillTextSelected: {
    color: colors.white,
  },
  toggleQuestionCard: {
    padding: 14,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  toggleChoiceRow: {
    flexDirection: "row",
    gap: 10,
  },
  toggleChoiceButton: {
    flex: 1,
    height: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  toggleChoiceButtonSelected: {
    backgroundColor: colors.primary,
  },
  toggleChoiceButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  toggleChoiceButtonTextSelected: {
    color: colors.white,
  },
  summaryCard: {
    marginBottom: 8,
    padding: 18,
    borderRadius: 26,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  summaryLabel: {
    marginBottom: 7,
    fontSize: 15,
    fontWeight: "800",
    color: colors.text,
  },
  summaryRatingRow: {
    marginBottom: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  summaryRating: {
    fontSize: 39,
    lineHeight: 44,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -1,
  },
  summaryQuality: {
    marginBottom: 6,
    fontSize: 16,
    fontWeight: "800",
    color: colors.primary,
  },
  summaryReviews: {
    maxWidth: 150,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textMuted,
  },
  summaryDetails: {
    flex: 1,
    maxWidth: 190,
    justifyContent: "center",
    gap: 8,
  },
  summaryDetailText: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: "right",
    color: colors.textMuted,
  },
  bottomActions: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 12,
    backgroundColor: colors.background,
  },
  submitButton: {
    minHeight: 58,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    gap: 12,
    ...shadow,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.white,
  },
  fallbackContainer: {
    flex: 1,
    padding: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  fallbackCard: {
    width: "100%",
    padding: 22,
    borderRadius: 28,
    alignItems: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  fallbackIconCircle: {
    width: 58,
    height: 58,
    marginBottom: 16,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryLight,
  },
  fallbackIcon: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.primary,
  },
  fallbackTitle: {
    marginBottom: 8,
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
    textAlign: "center",
  },
  fallbackDescription: {
    marginBottom: 20,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textMuted,
    textAlign: "center",
  },
  primaryFallbackButton: {
    width: "100%",
    minHeight: 52,
    marginBottom: 10,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  primaryFallbackButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.white,
  },
  secondaryFallbackButton: {
    minHeight: 42,
    paddingHorizontal: 18,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryFallbackButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.primary,
  },

  successToastOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },

  successToastCard: {
    minHeight: 58,
    paddingLeft: 10,
    paddingRight: 18,
    borderRadius: 999,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: "#D8EEDC",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    ...shadow,
  },

  successToastIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF8EF",
  },

  successToastText: {
    color: colors.text,
    fontSize: 14.5,
    fontWeight: "800",
    letterSpacing: -0.15,
  },

  buttonPressed: {
    opacity: 0.75,
    transform: [
      {
        scale: 0.97,
      },
    ],
  },

  primaryButtonPressed: {
    opacity: 0.86,
    transform: [
      {
        scale: 0.98,
      },
    ],
  },
});

export default styles;
